### ISSUE TITLE
Error while importing latest dump [robokop-kg]

### ISSUE THREAD

**Issue by Prakash2403** [NCATS-Gamma/robokop-interfaces#42]
Tried to import the latest dump: `graph.9.9.19.dump.db.`

Got this error. Please help.
```
robokop-interfaces/scripts/setup_neo4j_index.py:3: DeprecationWarning: The 'neo4j.v1' package is depr"""Get Neo4j index setup cypher."""
ecated, import from 'neo4j' instead
  from neo4j.v1 import GraphDatabase, basic_auth
Traceback (most recent call last):
  File "robokop-interfaces/scripts/setup_neo4j_index.py", line 11, in <module>
    predicates = list(row['predicate'] for row in result)
  File "robokop-interfaces/scripts/setup_neo4j_index.py", line 11, in <genexpr>
    predicates = list(row['predicate'] for row in result)
  File "/opt/conda/lib/python3.7/site-packages/neo4j/__init__.py", line 952, in records
    self._session.fetch()
  File "/opt/conda/lib/python3.7/site-packages/neo4j/__init__.py", line 527, in fetch
    detail_count, _ = self._connection.fetch()
  File "/opt/conda/lib/python3.7/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/opt/conda/lib/python3.7/site-packages/neobolt/direct.py", line 464, in _fetch
    response.on_failure(summary_metadata or {})
  File "/opt/conda/lib/python3.7/site-packages/neobolt/direct.py", line 759, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.DatabaseError: NOT PART OF CHAIN! RelationshipTraversalCursor[id=131071, open state with: denseNode=false, next=131071, mode=regular, underlying record=Relationship[131071,used=true,source=14701,target=2990,type=56,sPrev=131070,sNext=131069,tPrev=131860,tNext=130992,prop=611275,secondaryUnitId=-1,!sFirst,!tFirst]]

```

**Comment by Prakash2403** [comment]
Look [here](https://github.com/NCATS-Gamma/robokop/issues/490) for further discussion.
